# Generated by Django 4.2 on 2023-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ratings from 1.0 to 5.0', max_digits=3),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
